### ISSUE TITLE
Eliminating Gulp in favor of NPM scripts?

### ISSUE THREAD

**Issue by joshburgess** [pauldotknopf/react-dot-net#1]
Hi, interesting looking project! 

Would you be open to eliminating the use of gulp in favor of just using webpack & npm scripts for a simpler overall workflow?

I know Gulp is still really popular with the Angular & Aurelia guys, but it seems most React devs have moved towards simplifying project structure by just taking advantage of npm scripting.

Also, just out of curiosity, is there a way to eliminate the server-side routing/rendering after the initial load? Basically, is there an easy way to only use .NET to serve up the initial state of the app & speed up that first render and from then on treat it as a client-side-only single page app which communicates with an API back-end?

**Comment by pauldotknopf** [comment]
> Would you be open to eliminating the use of gulp in favor of just using webpack & npm scripts for a simpler overall workflow?

Absolutely. I noticed that nobody uses it these days, but it is the only thing I have had experience with. As long as we have all the same functionality (watch, etc), I am open to changing it. Now that I am thinking about it, I'm wondering how this will integrate with the new Gulp task runner that is built into Visual Studio? Maybe it isn't needed? Currently, in VS2015 with the ASP.NET Core beta bits, you can visualize all the gulp tasks, and run them individually. It probably is useless to have it integrated into VisualStudio, so I am game with having npm scripts instead.

> Also, just out of curiosity, is there a way to eliminate the server-side routing/rendering after the initial load?

This is the way things are currently. After the initial GET request, everything else is client-side, using JSON API's.

I have started implemented the default aspnet template (with registration, oauth, account mangement) on [another branch](https://github.com/pauldotknopf/react-dot-net/tree/aspnet-starter). It is more evident there that this is what is currently being done.

> Basically, is there an easy way to only use .NET to serve up the initial state of the app

This is exactly what is implemented currently. Maybe I should makes some docs to illustrate this better. Let me describe it a little bit here.

At each GET endpoint (initial page request), a separate ASP.NET MVC action handles it, which is how things are done traditionally in ASP.NET.

``` c#
public IActionResult Index(string greeting = "Hello!")
{
    // make some database calls, w/e.
    return View("js-/", new GreetingViewModel
    {
        Greeting = greeting
    });
}
```

However, there is some trickery going on here. Notice the view name? Any view name that is prefaced with `js-` is rendered via JavaScript. The path at the end of `js-`, in this case `/`, is the client-side URL. That is sent to react-router to render the appropriate route, and the model you pass it the initial state for your redux store.

I will have more examples soon, but something like this is totally be do-able.

``` c#
public IActionResult UserProfile(string userName)
{
    // make some database calls, w/e.
    return View("js-/user/pknopf", new
    {
        viewUserProfile = _userService.GetUserByUserName(userName)
    });
}
```

This would render the `/user/pknopf` route, with the initial state (the View Model) passed to the store. No network requests. After this page is loaded, the entire site is now navigated completely client-side. 

Now, the action described here is for the initial page load. You should probably keep these in their own controllers.

Then, you will want to create some WebAPI controllers, mounted at `/api`, that is used by the client only. The model returned from these WebAPI controllers should confirm to the initial store state provided be the full GET request (`UserProfile`) action method.

Does this clear some things up?

**Comment by pauldotknopf** [comment]
I just noticed, you live an hour drive from me. We should get a beer sometime!

**Comment by joshburgess** [comment]
Sure! By the way, I took interest in your project because I work at a .NET
shop in Tampa and I am currently trying to push them forward when it comes
to front-end tools & tech... If I had my way, I'd be using Node to serve up
the app, but I have to make sure they are comfortable with what we use, so
that's why I've been looking for the best solution to integrate MVC/Web API
with React/Node/NPM/Webpack/hot reloading/etc. on the client-side. None of
the other solutions I've seen so far are all that great.

I followed you on Twitter, by the way. Feel free to follow back so we can
chat on there if you want some help trying to convert over to npm scripts.
I'm the opposite of you, more experienced with npm than gulp, but we could
probably figure it out without too much trouble. I'm @_joshburgess on
Twitter.

**Comment by jdonaldson10** [comment]
@joshburgess sounds fairly similar to my scenario this past number of months.  I've had a fair bit of success getting this moving our newer dnx projects with npm scripts orchestrating webpack like so:

``` js
...
"scripts": {
  "start": "webpack-dev-server --config webpack.config.js --inline --progress --colors",
  "build": "webpack --config webpack.config.js --progress --profile --colors",
  "prod": "webpack -p --config webpack.prod.config.js --progress --colors"
},
...
```

@pauldotknopf I wouldn't worry massively about the task runner explorer stuff as there is a plugin to add [npm-script support](https://visualstudiogallery.msdn.microsoft.com/8f2f2cbc-4da5-43ba-9de2-c9d08ade4941) for those who prefer the gui experience. I would suspect that this will eventually get supported by default at some point too.

**Comment by joshburgess** [comment]
I find the task runners to be not very useful, to be honest. They seem to serve as another crutch for .NET devs to help them avoid learning to use the same workflows most other front-end devs are already using, and I think that's a not a great idea in the long run. I share your goal of wanting to limit the use of .NET as much as possible in order to not interfere with the front-end workflow, and I would rather just use the command line. It's easier to start/stop the dev server when desired this way too... but, yes, there are extensions for both webpack and npm task runners if desired. I tried both while trying out [VSReact](https://github.com/martijnboland/VSReact), but ultimately didn't find them to add much value.

For the npm scripts, I suggest we take a look at [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate). I don't think it needs to be mimicked or anything, but it shows a good idea of what is possible. It uses express for the dev server, but here are the script commands: 

"scripts": {
    "clean": "rimraf dist",
    "build:webpack": "cross-env NODE_ENV=production webpack --config webpack.config.prod.js",
    "build": "npm run clean && npm run build:webpack",
    "start": "node devServer.js",
    "lint": "eslint src"
  }

About the server-side rendering, I only skimmed over the documentation quickly, but I thought that it was being rendered server-side for each and every new view that was navigated to? I suppose this is for better performance, but it would be nice to be able to have the flexibility of routing only on the client-side after the initial shell of the app is loaded if so desired. Maybe, I am misunderstanding though. I will try to spend some time looking over the project soon.

**Comment by joshburgess** [comment]
Also wanted to add: Is there a way we could easily eliminate bower at the same time?

**Comment by pauldotknopf** [comment]
> About the server-side rendering, I only skimmed over the documentation quickly, but I thought that it was being rendered server-side for each and every new view that was navigated to? I suppose this is for better performance, but it would be nice to be able to have the flexibility of routing only on the client-side after the initial shell of the app is loaded if so desired.

If you disable JavaScript, every link will be a fresh request. With JavaScript enabled, all navigation is client-side, and whatever page you are on, F5 will do a fresh server-rendered request, returning the same page you are on.

**Comment by pauldotknopf** [comment]
> Is there a way we could easily eliminate bower at the same time?

We are not using bower. It was an artifact left over from a "File > New Project". I deleted it (58b38cc4) to avoid any confusion.

**Comment by pauldotknopf** [comment]
I think I'd rather keep gulp in there. I see no advantages of using npm scripts, except for the fact that everyone else is.

For the record, [este](https://github.com/este/este) is using gulp.

**Comment by joshburgess** [comment]
Okay, that's fine. I'll probably fork it and set it up without Gulp whenever I get some time just to have a project template available though... but I'll probably just use your "empty-template" branch, as I'm not really interested in all of the other extra stuff you are putting in the main branch anyway.

Just for the record, here are some really good blog posts which explain why some of us prefer the npm approach:

[Why We Should Stop Using Grunt & Gulp](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/)

[How to Use npm as a Build Tool](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)

**Comment by pauldotknopf** [comment]
Most of that author's gripes were with using gulp streams to handle minification/less/concat/etc. We are strictly using it as a build tool to run things in serial/parallel with dependencies. We use webpack for everything else.
