### ISSUE TITLE
Deploying to Azure

### ISSUE THREAD

**Issue by tysonnero** [pauldotknopf/react-dot-net#10]
Hey @pauldotknopf  - Have you successfully deployed this app to Azure. I gave it a try, but it's getting 500 errors when running. I'm not that experienced with Azure. Any ideas?

**Comment by pauldotknopf** [comment]
I have not. Do you have an error logs I could take a loot at?

**Comment by tysonnero** [comment]
Here's the error I'm seeing. I'll see if I can get more details.

Module     httpPlatformHandler
Notification       ExecuteRequestHandler
Handler    httpplatformhandler
Error Code     0x00000000
Requested URL      http://tyson-react-asp:80/
Physical Path      D:\home\site\wwwroot
Logon Method       Anonymous
Logon User     Anonymous

I also tried creating and publishing an new MVC 5 to Azure, and it work just fine.

**Comment by jcd79** [comment]
I had issues getting it running in Azure as well. As far as I remember it was a 500 error that occured before startup() etc was called at all.
I resolved it by setting the Azure Web App to run 64bit plaform and then I updated Target DNX version to x64 when publishing.

![pasted2](https://cloud.githubusercontent.com/assets/10612840/15047928/6c4b39dc-12e7-11e6-8120-89fad0873b49.png)

**Comment by tysonnero** [comment]
@jca79 Thanks. Will try now.

@pauldotknopf Does JSViewEngine support dnxcore50?

**Comment by tysonnero** [comment]
@jca79 Since I'm on the Free Tier, Azure isn't letting me switch to 64 bit.

**Comment by tysonnero** [comment]
@jca79 Okay, web to the Basic tier, turned on 64 bit, then restarted. No luck.

**Comment by tysonnero** [comment]
@jca79 Great news, I forget to change the Target DNX version to x64 when publishing like you said... Once I did that, I was game.

Thanks!

**Comment by pauldotknopf** [comment]
@tysonnero No support for JSViewEngine dnxcore50 at the moment. There is no reason why it can't though, we just need to add `#ifdef`s for the new API. I haven't done it because I haven't had a need for it yet. I will eventually. I am open to PR's :)
