### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by onthedoor** [pauldotknopf/react-dot-net#13]
Hi, 
This is a great project - just the technologies that I am aiming for! After getting the app to run on my local windows machine, I am trying to publish to Azure from visual studio  and end up with a server error 500. It's probably to do with getting node etc all set up and running, but above my level of technology.  Would you have any guidance?
Many Thanks

**Comment by pauldotknopf** [comment]
Check issue #10, they have managed to get it running on Azure.

**Comment by onthedoor** [comment]
Great - that solved the problem.

I am wanting to use this to create a Landing Page app and want to incorporate A/B testing into the React components.  Just wondering if you have any ideas on this?

**Comment by pauldotknopf** [comment]
@onthedoor, sorry, never done it.
