### ISSUE TITLE
Project name and namespace being "React" makes it difficult to rename

### ISSUE THREAD

**Issue by Legogris** [pauldotknopf/react-dot-net#18]
Suggestion: Call it something like ReactBoilerplate

**Comment by pauldotknopf** [comment]
Do you mean, doing a "Find All + Replace" is difficult?

I agree. This week, I plan on having a Yeoman generator completed that will generate a project with your desired name.

**Comment by Legogris** [comment]
Doing a replace all on 'React' breaks things, since, you know, React.

**Comment by pauldotknopf** [comment]
This is done. Yeoman project coming soon too.

**Comment by pauldotknopf** [comment]
Update: Yeoman is done.

``` bash
yo react-aspnet-boilerplate
```

[Here](https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/yeoman) is where the source for it lives.
