### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by dylinmaust** [pauldotknopf/react-dot-net#20]
This may be a stupid question, but is it possible to debug the server side code? I can't start the ReactBoilerplate project in Visual Studio. `dotnet run` starts the app, but can I attach to that process?

**Comment by pauldotknopf** [comment]
I believe VSCode has some preview extensions for debugging .NET Core applications. You could try that.

Why can't you open the file in Visual Studio?

**Comment by dylinmaust** [comment]
Please close this issue. I'm not really sure what the issue was. It must have been a Visual Studio specific issue, because I set the ReactBoilerplate project as the startup project, and clicking Start with Debugging opened a prompt, basically saying unable to start project. I may have had the server running on the CLI in the background accidentally.

Anyway, great project!

**Comment by pauldotknopf** [comment]
Thanks! Don't hesitate to ask any questions!
