### ISSUE TITLE
How to disable server rendering?

### ISSUE THREAD

**Issue by 0b01** [pauldotknopf/react-dot-net#28]
It's throwing too many errors for its own good. For example, document, window are not defined.

I would like to disable isomorphic rendering either selectively or once and for all.

Does anyone have any idea how to do this?

**Comment by pauldotknopf** [comment]
It is entirely up to the MVC actions to determine if it wasn't to use Razor or JavaScriptViewEngine.

You can return Views as you normally would, there. [here](https://github.com/pauldotknopf/react-aspnet-boilerplate/blob/master/src/ReactBoilerplate/Controllers/Home/HomeController.cs#L19). The JavaScriptViewEngine will render if your view name begins with `js-`.

Let me know if you need any more help, I'd be glad to help.

**Comment by kriskalish** [comment]
I'm trying to temporarily disable server-side rendering for testing purposes. I added the following code to my controller and it seems to work for the most part:

```csharp
            var html = @"
            <!DOCTYPE html>
            <html lang=""en"">
            <head>
            <meta charset=""UTF-8"">
                <title>Document</title>
                <link rel=""stylesheet"" type=""text/css"" href=""/pack/styles.css"">
            </head>
            <body>
                <div id=""content""></div>
                <script src=""/pack/client.generated.js""></script>
            </body>
            </html>";

            var resp = new ContentResult()
            {
                Content = html,
                ContentType = "text/html"
            };

            return resp;
```


However, it seems like once I do this, some of the styles are missing. For example, I'm using Material-UI and the padding between cards is missing. I don't see any errors in the console and I tried inspecting the DOM to do a comparison between the server generated DOM with the client-generated one and nothing stuck out at me.

If I'm doing something silly, I would appreciate some help!

**Comment by 0b01** [comment]
@kriskalish I created a separate stylesheet and put everything I need in there. Not the prettiest solution but it works!

**Comment by kriskalish** [comment]
It turns out the issue I was observing was not actually a lack of styles, but some subtle difference in how Chrome applied default styles to a form tag. In the server rendered page it would end up with a margin-bottom of 1em from "user agent stylesheet" and on the client rendered one it was lacking this.

I have a work around, so I'm considering this a non-issue.
