### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by sahilhaslani** [pauldotknopf/react-dot-net#7]
When I try to run this example I get this : 
Additional information: Couldn't load native assembly at C:\Users\xxxxx\AppData\Local\Temp\VroomJs.1.0.1.0\x86\VroomJsNative.dll

An exception of type 'System.Exception' occurred in VroomJs.dll but was not handled in user code

System.Exception was unhandled by user code
  HResult=-2146233088
  Message=Couldn't load native assembly at C:\Users\xxxx\AppData\Local\Temp\VroomJs.1.0.1.0\x86\VroomJsNative.dll
  Source=VroomJs
  StackTrace:
       at VroomJs.AssemblyLoader.LoadDll(String dllName, String architecture)
       at VroomJs.AssemblyLoader.EnsureLoaded()
       at React.Startup..ctor(IHostingEnvironment env) in C:\Software\samples\redux\react-aspnet-boilerplate\src\React\Startup.cs:line 44
  InnerException:

**Comment by pauldotknopf** [comment]
Does that library exist at "C:\Users\xxxx\AppData\Local\Temp\VroomJs.1.0.1.0\x86\VroomJsNative.dll"?

Added me on Skype, and I will help you debug the situation.

Skype: `paul.knopf1`

**Comment by sahilhaslani** [comment]
yes, it does exist at that location. Just says it cannot load. I tried using dependency walker, and see that it is showing the following dependencies as missing
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

Also I tried running procmon, and it seems to try to load this dll: api-ms-win-core-rtlsupport-l1-2-0.dll from all the path locations right before it fails. 

I will add you on skype as well.

**Comment by pauldotknopf** [comment]
Do you have the release-runtime version of VC2013 installed? X64 _and_ X86?

**Comment by sahilhaslani** [comment]
I did install those - still the same issue.

**Comment by pauldotknopf** [comment]
Update, we are now not using an embedded V8. We are using node.exe directly. It is currently implemented on the [`empty-template`](https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/empty-template) branch and `master` will be done soon.

Can you give it a shot?

**Comment by pauldotknopf** [comment]
Update, all branches are now RC2, and use a different javascript backend, so you shouldn't have this issue anymore.
