### ISSUE TITLE
React project load failed

### ISSUE THREAD

**Issue by tysonnero** [pauldotknopf/react-dot-net#9]
I've been able to open and run this solution in VS 2015 up until yesterday. What's happening is the React project is failing to load with the following errors:

C:\Projects\Samples\react-aspnet-boilerplate\src\React\React.xproj : error  : Import "Microsoft.VisualStudio.Web.ProjectSystem.UnconfiguredWebProject.IdleScheduler" could not be satisfied.

C:\Projects\Samples\react-aspnet-boilerplate\src\React\React.xproj : error  : Instantiated part(s) threw exception(s) from IDisposable.Dispose().

Any ideas?

**Comment by pauldotknopf** [comment]
What happens when you build with DNX directly?

```
dnu restore
dnx web
```

If that works, I suspect this issue has to do with the tooling for Visual Studio. Did you recently update Visual Studio, or the beta-bits for ASP.NET Core?

**Comment by tysonnero** [comment]
If I run those commands, everything works.

I didn't manually run any updates but maybe something happened in the background.

In fact, I can't open up any MVC 5 apps or create new ones... VS is jacked up! sigh...

**Comment by pauldotknopf** [comment]
Ya, that actual xproj stuff is entirely Visual Studio and the tooling for the new .NET Core, which isn't done. Before I look into anything with VS, we should wait for release versions, or maybe RC2 will fix it. I'll keep an eye on it.

One thing you can try is removing (and deleting) the .xproj. I think VS creates it automatically, based off of the `global.json`. You might have to make a change in `global.json` to trigger the update.

**Comment by tysonnero** [comment]
Thanks for the help. I tried what you said but didn't change anything. I'll keep at it.

**Comment by tysonnero** [comment]
Dude... it was a an extension called Productivity Power Tools that was causing the issue.

**Comment by pauldotknopf** [comment]
The irony...
